"""initial schema

Revision ID: 4fbe4cd99c4d
Revises: 
Create Date: 2026-09-15 16:46:01.612979
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fbe4cd99c4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='eventlevel'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_events_created_at', 'bot_events', ['created_at'], unique=False)
    op.create_table('daily_stats',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('ending_balance', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'WATCHING', 'ANALYZING', 'APPROVED', 'TRADED', 'REJECTED', name='tokenstatus'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_address'), 'tokens', ['address'], unique=True)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('volume_5m', sa.Float(), nullable=True),
    sa.Column('volume_1h', sa.Float(), nullable=True),
    sa.Column('volume_6h', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('buys', sa.Integer(), nullable=True),
    sa.Column('sells', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_snapshots_timestamp', 'market_snapshots', ['timestamp'], unique=False)
    op.create_index('ix_market_snapshots_token_id', 'market_snapshots', ['token_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'CONFIRMED', 'FAILED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('tx_signature', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_signature')
    )
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_token_id', 'orders', ['token_id'], unique=False)
    op.create_table('pairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('dex', sa.String(length=20), nullable=False),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', name='uq_pair_address')
    )
    op.create_index('ix_pairs_token_id', 'pairs', ['token_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('trailing_stop', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='positionstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.Enum('TAKE_PROFIT', 'STOP_LOSS', 'TRAILING_STOP', 'TIME_LIMIT', 'EMERGENCY', 'MANUAL', 'RISK_EVENT', name='exitreason'), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_status', 'positions', ['status'], unique=False)
    op.create_index('ix_positions_token_id', 'positions', ['token_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('signal', sa.Enum('BUY', 'SELL', 'HOLD', 'WATCH', 'REJECT', name='signaltype'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_token_id', 'signals', ['token_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('tx_signature', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='tradestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_order_id', 'trades', ['order_id'], unique=False)
    op.create_index('ix_trades_token_id', 'trades', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_token_id', table_name='trades')
    op.drop_index('ix_trades_order_id', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_signals_token_id', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_positions_token_id', table_name='positions')
    op.drop_index('ix_positions_status', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_pairs_token_id', table_name='pairs')
    op.drop_table('pairs')
    op.drop_index('ix_orders_token_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_market_snapshots_token_id', table_name='market_snapshots')
    op.drop_index('ix_market_snapshots_timestamp', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_tokens_address'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('daily_stats')
    op.drop_index('ix_bot_events_created_at', table_name='bot_events')
    op.drop_table('bot_events')
    # ### end Alembic commands ###
